.\" Manpage for viui.
.TH man 1 "02 Nov 2015" "1.0" "viui man page"
.SH DESCRIPTION
User Interface for the Visually Impared using the function keys of Michael Liao's Serial Brailler Keyboard
.SH USAGE
man Hotkeys, F1 help, F8 quit

viui Hotkeys, F1 to F8, open corrisponding program

nano Hotkeys, F1 help, F2 open file, F3 save file, F4 cancel, F5 cut, F6 uncut, F7 find, F8 quit

alpine, F1 help, F2 open file, F3 compose, F4 back, F5 journal, F7 setup, F8 quit

newsbeuter, F1 help, F2 open entry, F3 save story, F5 reload, F6 next unread, F7 open in browser, F8 quit

links, F1 help, F2 go to URL, F3 menu, F4 cancel, F7 find on page, F8 quit

irssi, F1 help, F2 connect <server>, F3 join <server>, F4 part, F5 query, F6 previous window, F7 next window, F8 quit

zsh, F1 help, F2 play, F4 cancel, F8 quit
 
.SH BUGS
The screenreaders will read the nohup initialise message
.SH AUTHOR
Kieran Gee (github.com/kism)